name: check-brew-gfortran
on: [push]
jobs:
  setup-macos-build-environment:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - run: brew info gfortran
      - run: which gfortran