name: build-macos-installer
on:
  push:
    tags:
      - "test-win-build-*"
jobs:
  setup-win-mingw-build-environment:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-opencv
        
      - name: 
        shell: msys2 {0}
        run: |
          ls /mingw64/include/opencv4
          ls /mingw64/include/opencv4/opencv2