name: build-macos-installer
on:
  push:
    branches:
      - "test-env-qt5"
jobs:
  setup-macos-build-environment:
    runs-on: macos-10.15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Select XCode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.2.1'
      - run: mkdir dev
      - run: |
          brew install tree

      - name: Install dependencies for project
        run: |
          brew install libxml2

      # Install Qt 5.15.2
      # NOTE: jurplel/install-qt-action@v2.14.0 hasn't supported Qt6.2.4
      - name: Install Qt 5.15.2
        run: |
          brew install p7zip
          python3 -m pip install setuptools wheel
          python3 -m pip install py7zr
          python3 -m pip install aqtinstall==2.1.0
          python3 -m aqt install-qt  mac desktop 5.15.2 -m debug_info -O $RUNNER_WORKSPACE/Qt
      
      # Build and Install Potrace library
      - name: Install Potrace
        #if: steps.cache-potrace.outputs.cache-hit != 'true'
        run: |
            cd dev
            curl http://potrace.sourceforge.net/download/1.16/potrace-1.16.tar.gz -o potrace-1.16.tar.gz
            tar -xvf potrace-1.16.tar.gz
            cd potrace-1.16
            ./configure --with-libpotrace
            make install
      
      - name: Install OpenCV
        run: |
          brew install opencv
      
      - name: QMake project
        run: |
          mkdir build
          cd build
          $RUNNER_WORKSPACE/Qt/5.15.2/clang_64/bin/qmake ${{ github.workspace }}/test/test.pro -spec macx-clang CONFIG+=qtquickcompiler
      - name: Compile (Build) project
        run: |
          cd build
          make qmake_all
          make -j10
      - name: Package built executable into dmg
        run: |
          cd build
          $RUNNER_WORKSPACE/Qt/5.15.2/clang_64/bin/macdeployqt TestQt.app -dmg -verbose=2
          tree .
      - run: brew list
      - run: tree /usr/local/lib
      #- name: Create Github Release
      #  uses: softprops/action-gh-release@v1
      #  #if: startsWith(github.ref, 'refs/tags/')
      #  with:
      #    files: build/TestQt.dmg