name: test-win64-build
on: 
  push:
    branches:
      - 'win64'
jobs:
  setup-win64-build-environment:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Chocolatey Dependencies
        uses: actions/cache@v3
        with:
          path: C:\ProgramData\chocolatey\lib
          key: choco-cache-${{ hashFiles('**/dependencies.config') }}
          restore-keys: |
            choco-cache-
      - run: choco install tree
      # Boost library
      - run: choco install boost-msvc-14.3
      # OpenCV Library
      - run: choco install opencv
      - run: dir
      - run: |
          $env:path
      - shell: python
        run: print("Hello world")
      - name: Build Potrace Library
        run: |
          choco install wget
          $env:path
          wget.exe http://potrace.sourceforge.net/download/1.16/potrace-1.16.tar.gz
          tar.exe -xvf potrace-1.16.tar.gz
      - run: tree C:\ProgramData\chocolatey
