name: learn-github-actions
on: [push]
jobs:
  setup-macos-build-environment:
    runs-on: macos-10.15
    steps:
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.2.1'
      - run: xcodebuild -version
      #- uses: actions/checkout@v3
      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: '14'
      #- run: npm install -g bats
      #- run: bats -v
