name: test-libpotrace
on: 
  push:
    branches:
      - 'potrace'
jobs:
  setup-macos-build-environment:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      # Determine xcode version
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.2.1'
      - run: mkdir ${{ github.workspace }}/dev/
      - run: |
          cd {{ github.workspace }}/dev/
          curl http://potrace.sourceforge.net/download/1.16/potrace-1.16.tar.gz -o potrace-1.16.tar.gz
          tar -xvf archive.tar.gz
          cd potrace-1.16
          ./configure --with-libpotrace
          make install
