name: test-win64-build
on: 
  push:
    branches:
      - 'win64'
jobs:
  setup-win64-build-environment:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: choco install tree
      # Boost library
      - run: choco install boost-msvc-14.3
      # OpenCV Library
      - run: choco install opencv
      - run: dir
      - run: echo $PATH%
      - name: Build Potrace Library
        run: |
          choco install wget
          wget http://potrace.sourceforge.net/download/1.16/potrace-1.16.tar.gz
          tar -xvf potrace-1.16.tar.gz
      - run: tree
      - shell: msys2 {0}
        run: |
          ls -al
          cd potrace-1.16
