name: test-qt-build
on: 
  push:
    branches:
      - 'qt'
jobs:
  test-build-qt-project:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - run: git checkout qt
      # Determine xcode version
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.2.1'
      - run: mkdir ~/dev/
      - uses: jurplel/install-qt-action@v2.14.0
        with:
          dir: ~/dev/ # optional
          version: 6.2.4 # optional, default is 5.15.2
          host: mac # optional
          target: desktop # optional, default is desktop
      - run: |
          brew install tree
          tree ~/dev/
      - run: |
          tree ${{ github.workspace }}
          ~/dev/Qt/6.2.4/macos/bin/qmake ${{ github.workspace }}/Test_Workflow/test.pro -spec macx-clang CONFIG+=qtquickcompiler && make qmake_all
          mkdir ~/build/
          make -j10 in ~/build/
      #- uses: actions/checkout@v3
      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: '14'
      #- run: npm install -g bats
      #- run: bats -v
